name: kafka_dart
description: High-performance Kafka client for Dart using librdkafka with Domain-Driven Design architecture.
version: 1.0.2-alpha
homepage: https://github.com/stefanoamorelli/kafka_dart
repository: https://github.com/stefanoamorelli/kafka_dart
issue_tracker: https://github.com/stefanoamorelli/kafka_dart/issues

environment:
  sdk: ^3.6.1

dependencies:
  ffi: ^2.1.3
  ffigen: ^19.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mocktail: ^1.0.4
  dartdoc: ^8.0.0
